### ISSUE TITLE
Arrow on evolutions going to the left

### ISSUE THREAD

**Issue by johnhearn** [damonsk/wardley-maps-examples#2]
The arrow head on evolutions that go left is pointing the wrong way.

<img width="186" alt="image" src="https://github.com/damonsk/wardley-maps-examples/assets/3379944/e711dbf8-a353-454b-a983-6afcbe40dc73">

The arrow should point left.

**Comment by johnhearn** [comment]
Example: 
```
component test [0.9, 0.2]
evolve test 0.1
```

**Comment by damonsk** [comment]
Hi @johnhearn 

My understanding is that components don't generally de-evolve so such a thing wouldn't appear on a wardley map. Is that the intent? 

Of course @swardley would be the person to confirm.

**Comment by swardley** [comment]
That is correct. The only circumstance when something “de-evolves” is when competition is removed either through a monopoly or it has become redundant. 

 

The far more common circumstance is when something is becoming a commodity BUT a vendor wishes it to remain a product or appear as custom built.  Hence the two main forms are:-

1. Something evolves to a more evolved state A -> A’

2. Vendor pretends something is less evolved B -> B’

Both are covered by the existing format:-

 

component A [0.49, 0.64]

component B [0.36, 0.61] 

evolve A->A' 0.8

evolve B->B' 0.3

**Comment by johnhearn** [comment]
My situation is that my company wants to beat competition by gradually customising an existing product. How do I represent that?

**Comment by swardley** [comment]
By way of example

```
title Our Plan

component The Market [0.67, 0.68] label [-51, -15]
evolve The Market -> Our Solution 0.3

annotation 1 [0.70, 0.51] In a competitive market, our aim is to "de-evolve" an existing product by either altering market dynamics or creation of some specific need such as status
annotations [0.12, 0.04]
```

Even if you achieve this, the competitive pressure will still ultimately drive the component back towards a product / heading towards a commodity unless you plan to restrict access to a select few i.e. altering market dynamics.
